version: 0.2
env:
  variables:
    TF_IN_AUTOMATION: "1"
phases:
  install:
    commands:
      - curl -fsSL https://releases.hashicorp.com/terraform/1.13.4/terraform_1.13.4_linux_amd64.zip -o t.zip
      - unzip t.zip && mv terraform /usr/local/bin/ && rm -f t.zip
  pre_build:
    commands:
      - terraform -version
      - echo "Init (dev)..."
      - terraform -chdir=infra/envs/dev init -input=false
  build:
    commands:
      - echo "Copy tfplan from plan_output artifact..."
      - cp "$CODEBUILD_SRC_DIR_PLAN_OUTPUT/infra/envs/dev/tfplan" "$CODEBUILD_SRC_DIR/infra/envs/dev/tfplan"
      - echo "Apply (dev)..."
      - terraform -chdir=infra/envs/dev apply -input=false -auto-approve tfplan
