version: 0.2
env:
  variables:
    TF_IN_AUTOMATION: "1"
    TF_VAR_billing_email: "david.tempestini@gmail.com"
    TF_VAR_codestar_connection_arn: "arn:aws:codeconnections:us-east-1:684441749407:connection/f2fc225f-b9aa-429b-ab41-50de95dc71d9"
    TF_VAR_github_repo: "dtempestini/health-bot"
phases:
  install:
    commands:
      - curl -fsSL https://releases.hashicorp.com/terraform/1.13.4/terraform_1.13.4_linux_amd64.zip -o t.zip
      - unzip t.zip && mv terraform /usr/local/bin/ && rm -f t.zip
  pre_build:
    commands:
      - terraform -version
      - terraform -chdir=infra/envs/dev init -input=false
  build:
    commands:
      - terraform -chdir=infra/envs/dev validate
      - terraform -chdir=infra/envs/dev plan -input=false -out=tfplan
artifacts:
  files:
    - infra/envs/dev/tfplan
