version: 0.2
env:
  variables:
    TF_IN_AUTOMATION: "1"
phases:
  install:
    commands:
      - curl -fsSL https://releases.hashicorp.com/terraform/1.13.4/terraform_1.13.4_linux_amd64.zip -o t.zip
      - unzip t.zip && mv terraform /usr/local/bin/ && rm -f t.zip
  pre_build:
    commands:
      - cd infra/envs/dev
      - terraform init -input=false
  build:
    commands:
      # Copy tfplan from the secondary artifact into the working directory
      - cp "$CODEBUILD_SRC_DIR_PLAN_OUTPUT/infra/envs/dev/tfplan" infra/envs/dev/tfplan
      - terraform apply -input=false -auto-approve tfplan
